<?php

 /**
 * Implements hook_theme().
 */
function ucb_campus_news_theme() {
	$config = \Drupal::config('ucb_campus_news.configuration');
	return [
		'cuboulder_today_filter_form_loader' => [
			'variables' => [
				'globalConfig' => [
					'siteURI' => $config->get('siteURI'),
					'baseURI' => $config->get('baseURI')
				],
				'data' => []
			]
			],
			'ucb_campus_news' => [
				'variables' => [
					'globalConfig' => [
						'siteURI' => $config->get('siteURI'),
						'baseURI' => $config->get('baseURI')
					],
					'data' => []
				]
				],
	];
}
